name: Push to Docker
on: [push]
jobs:
  build-and-push:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - name: Set up Python
      - name: Build and push image
        uses: actions/setup-python@v1
        with:
            python-version: "3.7"
      - name: Install Dependencies
        run: python3.7 -m pip install flask flask_bootstrap
      - name: docker build and push
        run: |
          docker build -t my-image .
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
          docker tag my-image:latest my-image:${{ github.sha }}
          docker push my-image:latest
          docker push my-image:${{ github.sha }}
