name: Push to Docker
on: [push]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push image
        uses: actions/setup-python@v1
        with:
            python-version: "3.7"
      - name: Install Dependencies
        run: python3.7 -m pip install flask flask_bootstrap
      - name: docker Login
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
      - name: docker build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-image:latest
      - name: docker push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-image:latest

